---
language: nix
env:
  global:
    - STORE=$HOME/nix-store
  matrix:
    - PYMKS_USE_FFTW=0
    - PYMKS_USE_FFTW=1
cache:
  directories:
    - $STORE
before_install:
  - sudo mkdir -p /etc/nix
  - echo "binary-caches = https://cache.nixos.org/ file://$STORE" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
  - mkdir -p $STORE
  - nix copy --to file://$STORE -f shell.nix nativeBuildInputs
install:
  - nix-shell --pure --command "echo 'run nix-shell'"
script:
  - nix-shell --pure --command "export PYMKS_USE_FFTW=$PYMKS_USE_FFTW; py.test --cov-fail-under=100"
  - nix-shell --pure --command "pylint --rcfile=.pylintrc setup.py pymks/__init__.py pymks/fmks pymks/fmks/tests"
  - nix-shell --pure --command "flake8 setup.py pymks/__init__.py pymks/fmks pymks/fmks/tests"
  - nix-shell --pure --command "black --check setup.py pymks/__init__.py pymks/fmks pymks/fmks/tests"
