---
language: python
env:
  - SFEPY_VERSION=release_2016.3 USE_SFEPY=1 PYMKS_USE_FFTW=1 PYTHON_VERSION=3
  - SFEPY_VERSION=release_2016.3 USE_SFEPY=1 PYMKS_USE_FFTW=0 PYTHON_VERSION=3
  - SFEPY_VERSION=release_2016.3 USE_SFEPY=1 PYMKS_USE_FFTW=1 PYTHON_VERSION=2
  - SFEPY_VERSION=release_2016.3 USE_SFEPY=1 PYMKS_USE_FFTW=0 PYTHON_VERSION=2
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$PYTHON_VERSION" == "2" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -y -n test-environment python="$PYTHON_VERSION"
  - source activate test-environment
  - conda install -q -y -n test-environment numpy scipy pytest scikit-learn matplotlib pytest-cov
  - conda install -q -y -n test-environment sympy cython pytables jupyter
  - if [[ "$PYMKS_USE_FFTW" -eq 1 ]]; then
      conda install -q -y -n test-environment -c conda-forge pyfftw;
    fi
  - if [[ "$USE_SFEPY" -eq 1 ]]; then
      git clone https://github.com/sfepy/sfepy.git ~/sfepy;
      cd ~/sfepy;
      python setup.py install;
      cd $TRAVIS_BUILD_DIR;
    fi
  - pip install pylint configparser nbval
  - unset VIRTUAL_ENV
  - pip install .
script:
  - if [[ "$PYTHON_VERSION" == "2" ]]; then
      py.test pymks;
    else
      py.test;
    fi
after_success:
  - #pylint --extension-pkg-whitelist=numpy pymks
